README.md
Added some initial README content
=> Draft of README content of new polyfill repo

lib/calendar.mjs
See https://github.com/tc39/proposal-temporal/pull/1624 and #7 for details.
=> Speed up non-ISO calendar perf about 10x

README.md
Check off the steps we've completed, and add a new step for the perf PRs that have been happening.
=> Update roadmap & check boxes for completed items

index.d.ts, lib/now.mjs, lib/temporal.mjs, test/exhaust.mjs, test/exports.mjs, test/now.mjs, test/usercalendar.mjs, test/usertimezone.mjs
Port of https://github.com/tc39/proposal-temporal/pull/1645
=> Rename Temporal.now => Temporal.Now

package.json
=> Removed a time command used to benchmark tests that was left behind

lib/init.js, lib/now.mjs, test/now.mjs
This ports over
https://github.com/tc39/proposal-temporal/commit/f2705277850ec33af1369748e8a8aad8eaae5a0a
https://github.com/tc39/proposal-temporal/commit/0421e3746768a56ccbb301451b942ec40ba0c4ee
=> Port normative changes from tc39/proposal-temporal.

README.md
This item can be checked off the list.
=> docs: Intl.DateTimeFormat caching is finished

lib/calendar.ts, test/datemath.mjs, test/intl.mjs
Port of https://github.com/tc39/proposal-temporal/pull/1761
=> Fix non-ISO months arithmetic

lib/calendar.ts, test/intl.mjs
Port of https://github.com/tc39/proposal-temporal/pull/1807
=> Fix crash setting `day` outside current JPN era

lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/plaindate.ts
This commit ports over
https://github.com/tc39/proposal-temporal/commit/6178ed35400fb56ef4013ce9d0163212ec096e57#diff-4f8f0de0a213714ceaf173c56843a7cdbbe8bda6fda71aca8652dc8b8678d42b.
=> Port more normative commits from tc39/proposal-temporal.

index.d.ts, lib/calendar.ts, lib/duration.ts, lib/instant.ts, lib/now.ts, lib/plaindate.ts, lib/plaindatetime.ts, lib/plainmonthday.ts, lib/plaintime.ts, lib/plainyearmonth.ts, lib/timezone.ts, lib/zoneddatetime.ts
We implement @@toStringTag, but it's not currently in the TS types. This PR fixes that.  There are some problems with the initial implementation that I'll discuss in follow-up comments.
=> Add @@toStringTag to TS types

lib/intrinsicclass.ts
ESGetIntrinsic is unused, and this now allows correct typing for types retrieved from the intrinsic container.
=> Type the intrinsics container, and remove usage of ESGetIntrinsic.

lib/regex.ts, test/regex.mjs
Cherry-picked from https://github.com/tc39/proposal-temporal/pull/1836
=> Tighten ISO parsing of month and day values

index.d.ts, lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/instant.ts, lib/intl.ts, lib/now.ts, lib/plaindate.ts, lib/plaindatetime.ts, lib/plainmonthday.ts, lib/plaintime.ts, lib/plainyearmonth.ts, lib/timezone.ts, lib/zoneddatetime.ts, test/ecmascript.mjs, test/validStrings.mjs
This drastically improves the ability of TypeScript to infer types of the functions that were previously within the container.
=> Collapse ecmascript.ts container.

README.md
Also add some new roadmap items and fix some extra whitespace.
=> Fix import in README.

lib/plaindate.ts, lib/plaindatetime.ts, lib/plainmonthday.ts, lib/plainyearmonth.ts
Port of https://github.com/tc39/proposal-temporal/pull/1858
=> Fix usage of ES.CalendarEquals

index.d.ts
Port of https://github.com/tc39/proposal-temporal/pull/1945
=> Fix TS types of RoundTo and TotalOf

index.d.ts
Port of https://github.com/tc39/proposal-temporal/pull/1964
=> Fix TS types for required CalendarProtocol methods

lib/ecmascript.ts, lib/regex.ts, test/duration.mjs, test/plaintime.mjs, test/regex.mjs, test/validStrings.mjs
This PR is a port of several recent proposal-temporal normative PRs:
* tc39/proposal-temporal#1950
* tc39/proposal-temporal#1952 (which was updated by tc39/proposal-temporal#1986)
* tc39/proposal-temporal#1956
=> Port of proposal-temporal PRs: 1950, 1952+1986, 1956

lib/calendar.ts
Port of https://github.com/tc39/proposal-temporal/pull/2034
=> Handle number-less DateTimeFormat Hebrew month

lib/calendar.ts
Port of https://github.com/tc39/proposal-temporal/pull/2033
=> Work around Firefox bug wtih Gregory era names

.github/workflows/test.yml, test/intl.mjs
Port of https://github.com/tc39/proposal-temporal/pull/2039
=> Add Node 17 to CI

test/intl.mjs
Port of https://github.com/tc39/proposal-temporal/pull/2055/commits/53808baf5841ede1301b02b3b203563e47f2bbb3
=> Fix Node14 tests broken by ICU update

test/intl.mjs
Fix Node 16 Intl test data. Port of https://github.com/tc39/proposal-temporal/pull/2064
=> Fix Node16 tests (port proposal-temporal/#2064)

index.d.ts, lib/calendar.ts
Port of https://github.com/tc39/proposal-temporal/pull/2056
=> Fix `Calendar.fields` return type (in index.d.ts) to match the spec

release-checklist.md
=> Document that releases should be published using NODE_ENV=production

lib/ecmascript.ts, test/timezone.mjs, test/zoneddatetime.mjs
Refs:
- https://github.com/tc39/proposal-temporal/pull/2090
=> Adjust ISO8601 representation for years between 1 BCE and 999 CE

CHANGELOG.md, package.json
With this PR, I intend to cherry-pick this commit along with the relevant single extra commit mentioned in the release notes (304c86dd) to create patch release 0.4.2, which will be directly off of the 0.4.1 branch, not from main.
=> Release version v0.4.2

lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/internaltypes.d.ts, lib/plaindate.ts, lib/plaindatetime.ts, lib/plainmonthday.ts, lib/plaintime.ts, lib/plainyearmonth.ts, lib/zoneddatetime.ts
These commits will be merged in, not squashed.
=> More upstream ports

test/expected-failures.txt
This test has long since been removed from Test262.
=> Remove outdated expected failure from test262.

.eslintrc.yml, tools/.eslintrc.yml, tools/package-lock.json, tools/package.json, tools/rebase-upstream-commits.ts, tools/rebasing.md, tools/tsconfig.json
This PR adds a copy of the rebasing script that I've been using to help me do rebases of the upstream proposal-temporal commits over to this repo.
=> Rebase tooling

tools/rebase-upstream-commits.ts
This will correctly resolve relative paths passed to the --repository flag, as well as start ensuring the tool is being pointed towards a Temporal repository.
=> Add repository resolution for rebase tool.

lib/ecmascript.ts, lib/zoneddatetime.ts, test/expected-failures-todo-migrated-code.txt, test/validStrings.mjs
Porting my first batch of commits from proposal-temporal using @12wrigja's [awesome rebase tool](https://github.com/js-temporal/temporal-polyfill/blob/main/tools/rebasing.md) for porting commits from proposal-temporal repo.
Lots of feedback on the tool is in #236.
If this PR looks good then I can migrate more commits later this week. 
I fixed up a mistake I made in one commit and in the process lost @ptomato's authorship of it. Whoops, sorry Philip!
=> Migrate commits from proposal-temporal 2023-04-12

index.d.ts
Adds a few changes that were missed in recent porting commits.
=> Polyfill: Sync index.d.ts with proposal-temporal

lib/ecmascript.ts, test/expected-failures-cldr42.txt, test/validStrings.mjs
Porting the final 9 commits to catch up to upstream!
=> Port commits from proposal-temporal 2023-04-26

lib/ecmascript.ts
Port another PR from upstream: [#2484](https://github.com/tc39/proposal-temporal/pull/2484)
=> Port proposal-temporal#2484

lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/timezone.ts, lib/zoneddatetime.ts, test/validStrings.mjs
Port a few more commits from proposal-temporal.
=> Port commits 2023-06-04

lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/plaindatetime.ts, lib/plaintime.ts
Brings up to date as of late October 2023. These are mostly updates to the removal of user code calls, in preparation for the introduction of calendar/timezone method records.
=> Batch of rebases - late October 2023

lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/intl.ts, lib/methodrecord.ts, lib/plaindate.ts, lib/plaindatetime.ts, lib/plainmonthday.ts, lib/plaintime.ts, lib/plainyearmonth.ts, lib/timezone.ts
Main change during this period is removing some BigInt arithmetic in Duration calculations.
=> Rebase through end of 2023

lib/bigintmath.ts, lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/instant.ts, lib/legacydate.ts, lib/math.ts, lib/timeduration.ts, lib/zoneddatetime.ts, test/all.mjs, test/math.mjs, test/timeduration.mjs, test/validStrings.mjs
Fewer commits this time, but a much larger diff. This is where the proposal changed to using time durations internally.
=> Rebase up to Februrary 2024

index.d.ts, lib/bigintmath.ts, lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/intl.ts, lib/plaindate.ts, lib/plaindatetime.ts, lib/plainmonthday.ts, lib/plainyearmonth.ts, lib/regex.ts, lib/zoneddatetime.ts, test/validStrings.mjs
A nice stack of 27 mostly-small commits.
=> Rebase up to April 2024

lib/duration.ts, lib/ecmascript.ts, lib/internaltypes.d.ts, lib/timeduration.ts, lib/zoneddatetime.ts, test/timeduration.mjs
This is only a small number of commits, but a large diff to go through. It includes the big refactor of how durations are rounded relative to ZonedDateTime.
=> Rebase through mid-May 2024

index.d.ts, lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/internaltypes.d.ts, lib/intl.ts, lib/plaindate.ts, lib/plaindatetime.ts, lib/zoneddatetime.ts, test/expected-failures-before-node16.txt, test/validStrings.mjs
Two minor normative changes and the rest is just refactoring.
=> Rebase through mid-September 2024

lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/internaltypes.d.ts
A batch of commits increasing conciseness using Duration Records.
=> Rebase: More from September 2024

index.d.ts, lib/calendar.ts, lib/duration.ts, lib/ecmascript.ts, lib/intl.ts, lib/intrinsicclass.ts, lib/primordials.ts, lib/zoneddatetime.ts, test/expected-failures-before-node16.txt, test/expected-failures-before-node18.txt, test/expected-failures-before-node20.txt, test/expected-failures.txt, test/validStrings.mjs
This is the last batch of the rebases. It consists of mostly small commits.
=> Rebase up to current

lib/duration.ts, lib/ecmascript.ts, lib/instant.ts, lib/legacydate.ts, lib/math.ts, lib/now.ts, lib/zoneddatetime.ts, package-lock.json, package.json
One more PR with a few (very minor) fixes and improvements in performance and bundle size.
=> Various improvements

.github/workflows/lint.yml, .github/workflows/test.yml
=> Test Node 24 in CI
