js-temporal/temporal-polyfill

- .github/workflows/test.yml
- .gitignore
- index.d.ts
- lib/duration.mjs
- lib/ecmascript.mjs
- lib/instant.mjs
- lib/intl.mjs
- lib/now.mjs
- lib/plaindate.mjs
- lib/plaindatetime.mjs
- lib/plainmonthday.mjs
- lib/plaintime.mjs
- lib/plainyearmonth.mjs
- lib/zoneddatetime.mjs
- package-lock.json
- package.json
- test/intl.mjs
* update version to 0.1.0
* copy recent code & test changes from original repo
* switch CI tests to run Node 14 and 16 (remove 15)
* run prettier --fix
* update dependencies
* update .gitignore
> Prepare for alpha (0.1.0) release

- lib/ecmascript.mjs
Creating Intl.DateTimeFormat instances in V8 is very slow and memory heavy. GetFormatterParts and GetCanonicalTimeZoneIdentifier are functions that are called many times when using Temporal, and they used to create new instances of Intl.DateTimeFormat for each call. In this commit, we cache them using the time zone identifier as the key.
It should be noted that doing the same to SystemTimeZone was deliberately avoided. This is due to the fact that the user's time zone may change during the execution of a program. An example is calling Temporal.now.zonedDateTimeISO() which should always output the correct time zone. This shouldn't be a problem for server-sided code which usually doesn't (or rather, shouldn't) use the time zone from the environment for calculations.
This fixes #7.
> Cache Intl.DateTimeFormat to reduce memory footprint

- lib/ecmascript.mjs
While migrating the source of the polyfill to TypeScript, tsc caught cases where native math operations were being used on big-integer polyfill objects as if they were native BigInts or numbers (`The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type.ts(2362)`). 
This PR fixes this error by converting them back to JS numbers, but should these be turned back into JS numbers, or should these operations be done using the big-integer library?
> Fix division issues caught by tsc in RoundDuration.

- lib/ecmascript.mjs
- lib/intl.mjs
- package.json
- test/intl.mjs
This PR speeds up `toLocaleString` and other operations that depend on the polyfilled `Intl.DateTimeFormat`. The fix was to prevent unnecessary creation of built-in `Intl.DateTimeFormat` objects, because the constructor of that built-in class is slooooooow. For more details about the underlying issue see: https://bugs.chromium.org/p/v8/issues/detail?id=6528
In local testing, speedup is about 2.5x for ZDT toLocaleString calls.  The sample code below runs in about 1800ms in the playground of the current main branch, and about 700ms in the playground of the PR branch. 
```js
(() => {
start = Date.now();
for (i = 0; i < 1000; i++) {
Temporal.ZonedDateTime.from('2020-01-01[America/Los_Angeles]').toLocaleString();
}
total = Date.now()-start;
console.log(`${total}ms`);
}) ()
```
> Speed up `toLocaleString` ~2.5x by reducing creation of `Intl.DateTimeFormat` instances

- lib/calendar.mjs
- lib/duration.mjs
- lib/ecmascript.mjs
- lib/intl.mjs
- lib/intrinsicclass.mjs
- lib/plaindate.mjs
- lib/plaindatetime.mjs
- lib/plainmonthday.mjs
- lib/plaintime.mjs
- lib/plainyearmonth.mjs
- lib/zoneddatetime.mjs
The existing eslint config doesn't seem to mind the lets currently, but does once the files are migrated. Splitting this into a separate PR makes the TypeScript source migration PR easier to review.
> Change let->const to satisfy lint checks for TS sources.

- index.d.ts
The TS types file is missing overloads for `PlainDate.prototype.toZonedDateTime()` when the argument is a timezone string or a TimeZoneProtocol object.
The current TS types support only object-bag arguments like these:
```ts
Temporal.Now.plainDateISO().toZonedDateTime({ timeZone: 'Asia/Tokyo' })
Temporal.Now.plainDateISO().toZonedDateTime({ timeZone: 'Asia/Tokyo', plainTime: '10:00' });
```
This PR adds TS types for the following overloads which work fine in the polyfill and spec but cause errors in TS: 
```ts
Temporal.Now.plainDateISO().toZonedDateTime(Temporal.Now.timeZone());
Temporal.Now.plainDateISO().toZonedDateTime('Asia/Tokyo');
```
> TS types for missing overloads of `PlainDate.p.toZonedDateTime()`

- package-lock.json
#27 didn't update the version in package-lock.json. I don't know what (if anything) this will break, but I assume they should be synced.
> Sync package-lock.json to package.json version

- lib/ecmascript.ts
File extensions are mandatory in ESM imports – q.v.
https://nodejs.org/api/esm.html#esm_mandatory_file_extensions.
> Add '.js' suffix to ecmascript imports

- index.d.ts
(port of https://github.com/tc39/proposal-temporal/pull/1732) 
* Rename all XxxLike types to include the Plain prefix
* Add PlainDateTime and ZonedDateTime to PlainTimeLike type (see https://github.com/tc39/proposal-temporal/issues/1707)
> Fix XxxLike TS types

- index.d.ts
- lib/calendar.ts
- lib/duration.ts
- lib/instant.ts
- lib/now.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plaintime.ts
- lib/plainyearmonth.ts
- lib/timezone.ts
- lib/zoneddatetime.ts
This PR modifies implementation files to import types from index.d.ts.  Now, type mistakes will be easier to catch.
Example: I found a type bug in the ZonedDateTimeISOFields declaration. This bug is fixed here too.
> Import types in implementation and fix a type bug

- lib/init.cjs
- package.json
- rollup.config.js
Node will treat all files (including those in dist/) as ESM within the
Temporal source due to setting "type":"module". Renaming these files to
use the cjs file extension tells Node to ignore this setting and treat
the content of those files as CommonJS.
> Rename all non-ESM build artifacts to use the cjs file extension.

- .gitignore
- .npmignore
- .vscode/launch.json
This PR adds a launch.json debug configuration file that VS Code users can use for one-click IDE debugging of either Demitasse or (coming soon once #41 is merged) Test262 tests.  
Demitasse test debugging "just works".  You should be able to set breakpoints inside Demitasse tests and the debugger will break there.
Test262 debugging has more quirks.  Notably, breakpoints don't work inside the Test262 test runner because there's no sourcemap pointing from the executing code back to the original test sources. This may not be worth solving anyways, because I suspect that generating sourcemaps for every test file would take a loooooooong time!
What *does* work is to place a `debugger;` statement inside a Test262 test that you want to debug. Execution will pause at the `debugger` statement and …
> Add VS Code configs for IDE debugging of tests

- .eslintrc.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- lib/ecmascript.ts
- lib/regex.ts
- package-lock.json
- package.json
Now that #57 is merged, it's easy to find which functions aren't used via [ts-prune](https://github.com/nadeesha/ts-prune).  This PR:
1. Deletes functions that aren't used at all
2. Removes `export` from functions that are never used (including tests) outside the file where they are declared. Fixes #63.
3. Adds a CI test for ts-prune so we can catch future cases of orphaned code or unused exports.  
4. While I was editing the GH actions config, I noticed that we weren't calling ESLint in CI tests, so I added that too.
**Deleted Functions Info**
According to `ts-prune`, the following 6 functions in ecmascript.ts weren't used:
* `RegulateISODateTime`
* `CastIfDefined`
* `CalendarCompare`
* `SubtractDate`
* `AssertPositiveInteger`
* `ToTemporalDurationOverflow`
After those were deleted, …
> Remove unused ecmascript.ts functions and un-export unused exports

- lib/intrinsicclass.ts
- package-lock.json
- package.json
This PR brings all dependencies (except Demitasse) up to latest. I mainly did this now to get TS 4.4 which includes some significant improvements to type inference based on upstream code.
It will also hopefully quiet the annoying security warning at the top of this page. 😄 
Also adds a new package.json script to make updating deps easier in the future. Now you can run `npm run update` which will update all non-Demitasse deps in package.json to `latest`. Just remember to run `npm i` afterwards to actually install the new deps!  
Note that I didn't install `npm-check-updates` locally because it would have brought in ~300 dependencies. Given that this is run only rarely, a locale install wasn't needed; using `npx` was fine.
Also re-ran prettier on all files, which resulted in one minor …
> Update dependencies (except Demitasse) and make it easier to update deps in the future

- index.d.ts
This PR ensures that the TS types for methods of the Calendar and CalendarProtocol types now correctly type `options` as optional.
This PR should be ported over to proposal-temporal too.
> Make `options` optional in TS types of Calendar and CalendarProtocol methods

- index.d.ts
In the spec and polyfill, the `calendar` parameter in Temporal constructors accepts a string as well as a CalendarProtocol. This PR updates the remaining types where `string` was previously missing in type declarations.
> Update types of PlainMD/YM constructors `calendar` param so that strings are also accepted

- lib/calendar.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plaintime.ts
- lib/plainyearmonth.ts
- lib/zoneddatetime.ts
This PR makes minor refactors to runtime type checks to make that validation more TS-friendly:
* Replace use of `ES.Type` for validating `Object` with a new type guard `IsObject` function. The function is overloaded so unknown values are typed as `Record`, while known types like `DurationLike | string` are simply stripped of primitive types while leaving the object types. As a nice side effect, this should reduce bundle size a little bit.
* For the other uses of ES.Type (there were only <5 of them), converts to simple `typeof` checks which provide the same type-narrowing benefit as type guard functions.
* Removes the ES.Type function.
* Adds type annotations to make all IsTemporalXxx into TS type guards.
@ptomato what do you think about whether I should port the ES.Type=>{IsObject, …
> Make runtime type checks TS-friendly

- .github/workflows/test.yml
- .gitignore
- .gitmodules
- package-lock.json
- package.json
- test/expected-failures.txt
- test/parseResults.js
- test/preprocessor.test262.cjs
- test/test262.sh
The Temporal test262 tests are being removed from tc39/proposal-temporal
(see https://github.com/tc39/proposal-temporal/pull/1853 ) and moved
to tc39/test262 where they will continue to be developed. Run them from a
git submodule so we can pull in new upstream versions when we are ready
for them.
Instead of cloning tc39/proposal-temporal to run the tests, we copy the
relevant parts of its test262 CI script. The files expected-failures.txt,
parseResults.js, and preprocessor.test262.cjs are copied from there as
well.
> Run the upstream test262 tests

- test/test262.sh
The (existing) local debugging setup for VSCode uses environment variables, not arguments.
> Fix local debugging of test262

- lib/ecmascript.ts
- lib/timezone.ts
This PR aligns with the pattern we use for the Number constructor and other ES built-in objects, where the object is saved when the ecmascript.ts module is imported and that saved reference is used in place of `String()` elsewhere.
My only concern with this PR is whether it will impact perf in the case where the literal text `"String"` is special-cased into a fast path by JS engines. I'll check the test runtime before and after this change to see if perf looks like a problem.
UPDATE: I didn't see any huge perf impact.
> Save String constructor in ecmascript.ts at module load time

- index.d.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/plaindatetime.ts
- lib/plaintime.ts
- lib/zoneddatetime.ts
- test/duration.mjs
- test/expected-failures.txt
- test/instant.mjs
- test/plaindatetime.mjs
- test/plaintime.mjs
- test/zoneddatetime.mjs
Enable strings to be used as the param of `round` and `total` methods. Port of https://github.com/tc39/proposal-temporal/pull/1875.
Note that this will fail two Test262 tests because passing invalid strings to this method used to throw a TypeError but now will throw a RangeError. 
After #1875 is merged, those tests should start passing. For that reason, we should probably wait to merge this PR until #1875 has landed over in proposal-temporal.
> Allow string param for `round` and `total`

- lib/ecmascript.ts
This fixes #92 with the suggestions by @justingrant 
-   Accept 1+ non-alphanumeric characters as separators. No need to restrict to spaces.
-   Only look at the first character of the era, to match both "B" and "BC". Might as well make the comparison case-insensitive while we're at it.
Tested on Firefox Nightly 96.0a1, Firefox Developer 95.0b12 (with the previous behavior) and Chrome 96.0.4664.45
> Fix GetFormatterParts for Firefox Nightly

- test/validStrings.mjs
Since #1874, strings with Z UTC designator are disallowed for Plain types.
This was not yet reflected in the manual ISO string generator test.
> Update manual ISO string tests to account for disallowed Z

- lib/ecmascript.ts
- lib/intrinsicclass.ts
- lib/timezone.ts
- test/expected-failures.txt
When porting over [063dd4d7a33cef728db6744d68cb4a21a720290b](https://github.com/tc39/proposal-temporal/commit/063dd4d7a33cef728db6744d68cb4a21a720290b) I found when retrieving the `getOffsetNanosecondsFor` method we don't actually check the type is callable. Fixing this then lead me to remove the registration of the intrinsic, as it's now unused (`undefined` is not callable, and will throw a TypeError). The [corresponding function](https://github.com/tc39/proposal-temporal/blob/f2405e18f5f9fdf2d80250b1075f16f40547c911/polyfill/lib/ecmascript.mjs#L1759-L1769) in the proposal repo doesn't have this fallback either.
> Remove getOffsetNanosecondsFor fallback from polyfill

- lib/ecmascript.ts
Port of https://github.com/tc39/proposal-temporal/pull/1968
Also added a minor type safety cast that I missed when reviewing an earlier PR.
> Minor DRY fix for RoundDuration

- index.d.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/intrinsicclass.ts
- lib/legacydate.ts
- lib/slots.ts
- lib/timezone.ts
- lib/zoneddatetime.ts
- package-lock.json
- package.json
- test/ecmascript.mjs
JSBI has the following advantages over big-integer:
- it has better type-safety and mirrors native BigInt behavior (cannot mix native BigInt and number)
- has a babel plugin (not configured in this PR) that can transpile away JSBI entirely to use native BigInt instead, for code-size improvements. We should consider shipping a separate package (maybe this should be the default) using this that provides all the Temporal features and uses native BigInt, as I'd guess this will be more common than users wanting to use this on platforms without native BigInt.
JSBI has some disadvantages:
- the JSBI.BigInt factory function does NOT support automatically converting native BigInt to a JSBI instance at runtime. Instead, in places where the type might be a native BigInt, we use `ES.ToBigInt` to …
> Use JSBI instead of big-integer

- lib/index.ts
- lib/init.ts
- lib/intl.ts
Port of https://github.com/tc39/proposal-temporal/pull/1974
> Ensure that Temporal prototypes aren't writable

- lib/ecmascript.ts
- lib/regex.ts
- lib/timezone.ts
- lib/zoneddatetime.ts
- test/duration.mjs
- test/zoneddatetime.mjs
Three commits here to catch up with recent PRs over in proposal-temporal:
* Throw RangeError for invalid offset strings - tc39/proposal-temporal#1976
* Remove zoneRequired param - tc39/proposal-temporal#1979
* Refactor ecmascript.ts - tc39/proposal-temporal#1976 and tc39/proposal-temporal#1980 (the latter was a subset of the lines covered by the former PR, so I just combined into one commit)
> Catch up on proposal-temporal PRs

- index.d.ts
- lib/calendar.ts
Port of https://github.com/tc39/proposal-temporal/pull/1977 and https://github.com/tc39/proposal-temporal/pull/1983 to fix a bunch of smaller issues with non-ISO calendar. 
This is (hopefully!) the last ported PR so that #109 can be limited to type changes only. 
We should merge this PR only after https://github.com/tc39/proposal-temporal/pull/1977 is approved and merged.
> Port non-ISO calendar fixes from proposal-temporal PRs #1977 and #1983

- lib/calendar.ts
The implementation of non-ISO calendars has always been a bit sloppy and confusing since I wrote it as a proof-of-concept a year ago. Now that non-ISO calendar implementations are fully typed in #109, it's easier and safer to refactor them into a more maintainable set of ES6 classes. The inheritance structure is below, with bold classes are actual ICU calendars, the non-bold ones are base classes. 
* HelperBase - shared code for all non-ISO calendars
* **HebrewHelper**
* **PersianHelper**
* **IndianHelper**
* GregorianBaseHelper
* **RocHelper**
* **BuddhistHelper**
* **GregoryHelper**
* **JapaneseHelper**
* OrthodoxBaseHelper
* **EthiopicHelper**
* **EthioaaHelper**
* **CopticHelper**
* ChineseBaseHelper
* **ChineseHelper**
* **DangiHelper**
* IslamicBaseHelper
* **IslamicHelper**
* …
> Refactor non-ISO calendars to use ES6 classes

- index.d.ts
This was missed out in https://github.com/js-temporal/temporal-polyfill/commit/46b663cfe40c6b9381263d166615f8d5f7fadef5.
> Include the valueOf function in Temporal.Duration.

- index.d.ts
- lib/ecmascript.ts
Extends TS tsupport for property-bag form of Calendar-like and TimeZone-like params in Temporal methods. Fixes https://github.com/js-temporal/temporal-polyfill/issues/118
Also allows `Temporal.Calendar` instances to be used in the `Intl.DateTimeFormatOptions` type. (Previously only string IDs were allowed.) Fixes https://github.com/js-temporal/temporal-polyfill/issues/124.
Note that fixing https://github.com/tc39/proposal-temporal/issues/2005 will further extend the types that can be passed into the `calendar` and `timeZone` properties of `Intl.DateTimeFormatOptions`. But that requires a spec change and polyfill code change, so in this PR we'll only extend `Intl.DateTimeFormatOptions` to what's supported by the current spec and polyfill.
> Update TS types of TimeZone-like/Calendar-like params to match spec and polyfill

- lib/calendar.ts
I think this got copied as part of a previous calendar refactoring and the original never cleaned up.
> Remove duplicate CalendarImpl definition.

- lib/ecmascript.ts
`prim` is now correctly inferred as either bigint or string, so casting is no longer needed.
> Remove a cast to bigint that is no longer needed.

- lib/ecmascript.ts
- test/ecmascript.mjs
As a follow-up to #97 this adds tests for the relevant code parts and lets it throw on unexpected input (instead of failing with NaN values later somewhere else)
Should a browser change the format again, it will fail with a helpful error message in the correct place.
> GetFormatterParts tests and error cases

- lib/ecmascript.ts
- test/timezone.mjs
When passed very far-past or very far-future dates,`TimeZone.p.get(Next|Previous)Transition()` currently takes minutes of 100% CPU to finish because those methods include a loop that makes expensive system calls for every 2 weeks until it finds a transition. For periods where there are no transitions, this loop will run millions of times which is time consuming.
Note that native implementations have access to the TZDB data directly so this is not an issue there. We could in theory bundle TZDB data (or simply bundle a shorter list of per-timezone data showing the earliest and oldest TZDB rules for each) but doing so would add a lot of complexity (and at least some bundle size) to this polyfill for minimal benefit, so solving the problem with optimization is, IMHO, preferable.  
This PR …
> Fix `TimeZone.p.getXxxTransition()` worst-case perf

- lib/calendar.ts
- lib/ecmascript.ts
- lib/timezone.ts
Add missing branding checks for Timezone and Calendar toString and toJSON.
Port of https://github.com/tc39/proposal-temporal/pull/1995.
Reject '-000000' as an extended year value.
Port of https://github.com/tc39/proposal-temporal/pull/1992
Bump test262.
> Port recent changes from tc39/proposal-temporal.

- lib/intl.ts
This causes Test262 errors in Safari for
ZonedDateTime/prototype/toLocaleString/options-conflict (and possibly
others).
> Remove erroneous options from Safari's Intl.DateTimeFormat resolvedOptions.

- lib/calendar.ts
- test/intl.mjs
This PR fixes two bugs with lunisolar calendars: 
1. https://github.com/js-temporal/temporal-polyfill/commit/932810be1306a30d4c95fc88c54c64abe7fb1bf9 fixes #149 which could happen when adding/subtracting years to/from a lunisolar calendar date.
2. https://github.com/js-temporal/temporal-polyfill/commit/80611d584b880d7c9af68327b49bdc9ede050eed fixes another bug in the Hebrew calendar that was exposed by new tests for (1)
The tests for (2) can't pass without (1), so it was most convenient to put the fixes into separate commits in the same PR. Hope this is OK, given that each of these are tiny changes. If not, I could split into two PRs.
> Lunisolar math fixes

- package.json
Before this Typescript would fail to resolve the types for the package when configured to use module: "Node16" (new in Typescript 4.7).
`main.ts:1:26 - error TS7016: Could not find a declaration file for module '@js-temporal/polyfill'.`
Repro available at https://github.com/jonasb/typescript-error-repro/tree/typescript-4.7-esm-node16-js-temporal
> Add types to exports/./import to support Typescript Node16

- lib/ecmascript.ts
This bug was introduced in a25a878665dc7b73e101f69d5b127a5439595653 as a
typo - division drops the last 6 digits of the current milliseconds,
when instead we wanted to use them.
This was causing Temporal/Now/instant/return-value-value to be flaky in my testing, as sometimes time appeared to go backward by a small number of nanoseconds.
> Fix mathematical error when computing System UTC Epoch nanoseconds.

- lib/calendar.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/plaindatetime.ts
- lib/plaintime.ts
- lib/zoneddatetime.ts
Similar to other rebases, I intend for this to be merged as-is without squashing.
The typing for GetTemporalUnit is interesting - ideally, I'd like to find a way to avoid all the casts within the function itself and avoid needing overloads, but I can't seem to get TS to recognize that when the default empty array (typed as `never[]`) is used as the `extraValues` property that it expands to `never` in the return type (which is the union identity).
> Editorial: Simplify operations (#2248)

- lib/calendar.ts
- test/calendar.mjs
between two identical dates.
Fixes #180.
> Bail out early in non-ISO Calendars when calculating the duration

- lib/calendar.ts
- lib/ecmascript.ts
- lib/internaltypes.d.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plainyearmonth.ts
- lib/zoneddatetime.ts
- test/expected-failures.txt
Like other spec port PR's, I will merge this as-is without squashing to retain history.
> More spec ports, and small updates to GetTemporalUnit typings.

- copy-types.mjs
- package.json
> add script to copy types for commonjs module system

- CHANGELOG.md
- package-lock.json
- package.json
There's still other porting work to be done to bring over changes from the spec polyfill, but I'd like to cut a release here so that we can be sure the fixes included in https://github.com/js-temporal/temporal-polyfill/pull/184 actually work for the community.
> Release 0.4.3

- README.md
The anchor of the link to other polyfills in the tc39/proposal-temporal repository has changed from `polyfill` to `polyfills`.
> Fix the link to other polyfills

- package-lock.json
- package.json
- runtest262.mjs
This allows the test262 runner to update expected-failure files via a command line flag:
```
npm run test262 -- --update-expected-failure-files
```
If we use this a lot we could add that to package.json.
> Use a command line parser in runtest262.

- lib/slots.ts
- test/test262.sh
#164
Implements globalThis slots mentioned in https://github.com/js-temporal/temporal-polyfill/issues/164#issuecomment-1185775627 to fix the slots issue with dual package hazard.
> Implements globalThis slots

- runtest262.mjs
- test/expected-failures-cldr42.txt
- test/expected-failures.txt
V8 broke Test262 by releasing a regression that caused the output of `Intl.DateTimeFormat.p.format` to differ from `Intl.DateTimeFormat.p.format`. See https://bugs.chromium.org/p/chromium/issues/detail?id=1416538.
Until V8 fixes itself and those fixes get into CI, we'll skip the now-broken tests.
> Temporarily work around Test262 tests broken by V8 bug #1416538

- lib/ecmascript.ts
- lib/legacydate.ts
ToBigInt is somewhat redundant with the JSBI.BigInt function (which implements the BigInt constructor behavior).
The ToBigInt conversion in ToTemporalInstant is unnecessary as JSBI.multiply will always return a JSBI, and this is passed to the ToBigInt AO as part of the Temporal.Instant constructor ([spec ref](https://tc39.es/proposal-temporal/#sec-temporal.instant)).
> Simplify some redundant BigInt operations.

- tools/rebase-upstream-commits.ts
This addresses some of the points raised in #236:
- Includes an explanation of how to handle updates to polyfill/lib/ecmascript.mjs from upstream
- new abort and finish commands that help end rebasing prematurely, throwing away or keeping your current rebase progress respectively.
-  > When a commit only updates the spec (no polyfill files) the tool still stopped.
This was a bug in the way calls to `git rebase --continue` were being handled - handling is now centralized to be consistent.
- The tool will attempt to clean up the `.temporal_rebase_tool` folder it creates when it thinks the rebase is done.
- Test262 no-op update handling might have improved - we check to see if the upstream submodule is changing before running the "handle test262 cases" logic, but I'm not 100% that will fix …
> Improvements to rebase tool.

- tools/rebasing.md
Document the Test262 runner's capability to automatically fix up the expected-failure files when a test starts passing during a rebase. Also document the `finish` and `abort` commands.
> Doc improvements for rebasing

- tools/rebasing.md
I've found that it's easier to just stay in the root directory throughout the rebase steps.
> Rebase tool docs: don't require changing to tools dir

- tools/rebase-upstream-commits.ts
ecmascript.mjs now merges properly into ecmascript.ts, so this warning is no longer needed.
> Rebase tool: remove warning about ecmascript.mjs

- CHANGELOG.md
- package.json
There is quite a lot to review here, and there's a couple more PRs that we should merge (and I'll update the release notes to include).
I wasn't quite sure where to put many of the changes in this release - observable changes in the order functions were called or properties were accessed ended up being something I skipped unless it sounded particularly important (e.g. sorted field access on property bags), but if those sorts of changes should be mentioned I'll have to take another pass over the commits to include the (many) relevant ones.
Similarly, there were lots of changes that are bug fixes, breaking changes, possibly both at the same time? Happy to reorganize the lists as people see fit - I don't have a good sense for whether fixing some of these bugs is likely to be a breaking …
> Release v0.4.4

- .github/workflows/lint.yml
- .github/workflows/test.yml
- lib/calendar.ts
Work around an ICU 73.1 bug (https://bugs.chromium.org/p/chromium/issues/detail?id=1173158) that was causing Test262 tests to fail. The workaround simply avoids using Intl.DateTimeFormat for Gregorian-based calendars, which enables these calendars to work properly for dates before the 1582-10-15 Gregorian switchover while also using less RAM and CPU.
This PR is stacked on top of #258, so you only need to review the top commit in this PR.
We'll wait to merge this until the corresponding Test262 PR (https://github.com/tc39/test262/pull/3848) is merged and this PR can be rebased on top of that one.
> Support Node 20 and work around Node 20 / ICU 73.1 bug

- .eslintrc.yml
- .prettierignore
- index.d.ts
- lib/calendar.ts
- lib/ecmascript.ts
- lib/intl.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plaintime.ts
- lib/plainyearmonth.ts
- lib/regex.ts
- lib/timezone.ts
- lib/zoneddatetime.ts
- package.json
- test/expected-failures-before-node18.txt
- test/expected-failures-es5.txt
- test/validStrings.mjs
This PR catches us up to  [4345a8cbe90bd140321d31549a0382d3cbf2546b](https://github.com/tc39/proposal-temporal/commit/4345a8cbe90bd140321d31549a0382d3cbf2546b) in the [tc39/proposal-temporal](https://github.com/tc39/proposal-tempora) repo. 
Only 173 more commits to go. (!!!) Thankfully only a fraction of those are polyfill commits, so hopefully it won't be too heavy of a lift.  Probably only 3-4 more PRs like this one.
> Port commits from proposal repo (2024-02-25 tranche)

- package.json
Allows bundlers to tree-shake out the temporal polyfill when it is imported but not used.
If (or when) in the future the polyfill patches the global object `"sideEffects"` may be changed to an array to declare the side effects of a specific entry (e.g. `@js-temporal/polyfill/global` has side effects while other entry points do not).
> Set package sideEffects to `false`

- index.d.ts
This pull-request fixes outdated links in index.d.ts file
> fix: update links in docs sections

- lib/calendar.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/internaltypes.d.ts
- lib/intl.ts
- lib/intrinsicclass.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plaintime.ts
- lib/plainyearmonth.ts
- lib/timezone.ts
- lib/zoneddatetime.ts
- test/ecmascript.mjs
- test/validStrings.mjs
I did an afternoon of rebasing and have completed up to the normative changes that landed in September 2023. That seems to be a nice sized batch for reviewing.
Note, I skipped https://github.com/tc39/proposal-temporal/commit/36f288a64f6e1fde74002c2d8131b17980283f2b because the implementation for transition-finding has already diverged so much from the proposal-polyfill, and already had a different lookahead.
> Rebase up to September 2023

- tools/rebase-upstream-commits.ts
I went to do some rebasing and found the rebase tool didn't really work with `--exec` — whenever the tests would fail in the exec step, it was impossible to run `trt continue` or `trt finish`; the tool would just think it was all done, and exit immediately. Here's a fix.
Note that to move on after an exec failure, you now have to have run `trt exec` to mark the last commit as having succeeded. Ideally you wouldn't have to do this and would just be able to run `trt continue`, but I didn't immediately see a way to implement that without a large refactor.
> rebase-tool: Allow 'continue' and 'finish' to work in exec step

- lib/duration.ts
- lib/ecmascript.ts
- lib/plaindate.ts
- lib/zoneddatetime.ts
- test/expected-failures.txt
This brings the polyfill up to date as of early October 2023. The changes are mainly around removing unnecessary user calls.
> Batch of rebases - early October 2023

- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/internaltypes.d.ts
- lib/intl.ts
- lib/intrinsicclass.ts
- lib/methodrecord.ts
- lib/now.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plaintime.ts
- lib/plainyearmonth.ts
- lib/timezone.ts
- lib/zoneddatetime.ts
This one is very few commits but a lot of changed lines. It corresponds pretty much to https://github.com/tc39/proposal-temporal/pull/2519
I'll be the first to admit that the Typescript annotations in `methodrecord.ts` are not very good, and there's a lot of `@ts-expect-error` needed to get it to compile. However, note that method records were removed from the proposal in June 2024. So I didn't want to spend a lot of time getting the types just right, since it'll be deleted in a forthcoming PR anyway.
If there are any easy-to-implement suggestions to improve `methodrecord.ts` I'm happy to incorporate them, but if it's complicated I'd prefer to just leave it. The sloppy code will be gone soon enough!
> Update as of November 2023

- index.d.ts
- lib/calendar.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/now.ts
- lib/plaindatetime.ts
- lib/plaintime.ts
- lib/zoneddatetime.ts
- test/validStrings.mjs
Another stack of 25 commits. Most of them are either the more straightforward removals from the June 2024 changes, or improvements to the ISO 8601 grammar which were reflected in test/validStrings.mjs. (We have not yet gotten to the removal of calendars and time zones.)
> Rebase through end of June 2024

- lib/calendar.ts
- tools/rebase-upstream-commits.ts
One fix is for a merge conflict resolution that I messed up. The other is a solution for a weird error that I got while rebasing, where `git rebase` could not find my `.gitconfig` file.
> Two fixes that are not rebases

- lib/calendar.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/intrinsicclass.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plainyearmonth.ts
- lib/zoneddatetime.ts
Includes a refactor of calendar operations.
> Rebase through early October 2024

- runtest262.mjs
- test/expected-failures-cldr46.txt
ICU 76.1 / CLDR 46 got backported to Node 20.19 LTS, which is now in the GitHub CI. We need a CLDR 46 expected failures file until we can update to a version of test262 where this failure has been fixed.
> Add expected failures for CLDR >= 46

- lib/timeduration.ts
Downleveling this with the TypeScript compiler would add a runtime dependency on tslib. The TimeDuration object is private anyway and not exported to client code, so we don't strictly need this method to be private.
> Remove usage of private fields

- lib/calendar.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/instant.ts
- lib/internaltypes.d.ts
- lib/intl.ts
- lib/now.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plaintime.ts
- lib/plainyearmonth.ts
- lib/slots.ts
- lib/zoneddatetime.ts
- test/ecmascript.mjs
- test/validStrings.mjs
Here is a batch of commits from October 2024 all dealing with refactoring the way ISO Date-Time Records are used in the spec. It made the spec text more concise, so should do the same with this JS code. (Net -1k lines)
> Rebase: ISO Date-Time Record refactoring

- index.d.ts
- lib/calendar.ts
- lib/duration.ts
- lib/ecmascript.ts
- lib/internaltypes.d.ts
- lib/intl.ts
- lib/legacydate.ts
- lib/math.ts
- lib/plaindate.ts
- lib/plaindatetime.ts
- lib/plainmonthday.ts
- lib/plainyearmonth.ts
- lib/primordials.ts
- lib/timeduration.ts
- lib/zoneddatetime.ts
- test/expected-failures-before-node16.txt
- test/expected-failures-es5.txt
- test/expected-failures.txt
- test/timeduration.mjs
Second-to-last batch of rebases.
> Rebase up to December 2024

- package-lock.json
- package.json
- rollup.config.js
Produces a bundle size savings of about -3k minified, -1k minified and gzipped.
(I unfortunately didn't think of this before preparing the release, otherwise I'd have tried to include it.)
> Delete assertions using rollup strip plugin

- package-lock.json
- package.json
- rollup.config.js
Changex rollup's `keep_fnames` option from `true` to `false`.
My understanding is that this option will minify function names, for example the often-long internal exports in `ecmascript.ts`.
This change (and a minor change to run terser's compression 2x to save 85 bytes) reduces minified & gzipped size of `dist/index.cjs` to 36.3K. (a 3.7K reduction). ESM reductions are similar. I didn't apply this optimization to ES5 UMD builds because it caused all ES5 Test262 tests for `Temporal.prototype.*.name` to fail.
> Minify function names in prod builds

- .eslintrc.yml
- .github/workflows/test.yml
- lib/intl.ts
- package.json
- runtest262.mjs
- test/expected-failures-before-node22.txt
- test/expected-failures-before-node23.txt
- test/expected-failures-cldr42.txt
- test/expected-failures-cldr46.txt
- test/expected-failures.txt
Support Node 22 & 23. In addition to changing expected failures files for bugs that Node fixed, there were two Node changes that required polyfill code changes:
* Now that Node 22 supports offset time zones in Intl.DTF, we needed to stop throwing when these IDs were supplied, and we needed to guard against U+2212 (unicode minus) in offset time zone IDs because Node doesn't catch these (yet).
* Node 23 adds `Intl.DurationFormat`, and this PR fixes an infinite recursive loop (accidentally introduced in 19b00b2) that occurred if a native `Intl.DurationFormat` was present.
Fixes #323.
> Support Node 22 & 23
